name: coconut_analytics
profile: snowflake_trial
model-paths: [models]
analysis-paths: [analyses]
test-paths: [tests]
seed-paths: [seeds]
macro-paths: [macros]
snapshot-paths: [snapshots]
clean-targets:
  - target
  - dbt_packages

models:
  coconut_analytics:
    +materialized: table
